language: python
python:
  - "3.6.4"
cache:
  pip: true

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script:
      - mv config.py.simple config.py
      - python -m unittest

    - stage: docker
      sudo: required
      services:
      - docker
      before_install:
      - docker build -t lfzyx/buttersalt .
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push lfzyx/buttersalt
